# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Board.create!([
  { :image => "chess_board.jpg", :game_id => 1, :created_at => "2013-12-12 15:14:52", :updated_at => "2013-12-12 15:14:52" },
  { :image => "backgammon_board.jpg", :game_id => 2, :created_at => "2013-12-12 15:15:35", :updated_at => "2013-12-12 15:15:35" },
  { :image => "chess_board.jpg", :game_id => 3, :created_at => "2013-12-12 15:42:28", :updated_at => "2013-12-12 15:42:28" }
])



Game.create!([
  { :name => "checkers", :secure_room_code => "8a765328f6a9a3c28ea5d57e6eb34a50", :game_builder_id => nil, :created_at => "2013-12-12 15:14:52", :updated_at => "2013-12-12 15:14:52" },
  { :name => "backgammon", :secure_room_code => "50819076c4f7bb6895eff71c28ce4226", :game_builder_id => nil, :created_at => "2013-12-12 15:15:35", :updated_at => "2013-12-12 15:15:35" },
  { :name => "checkers", :secure_room_code => "7ff89e81a771d3250e23aed4b726031c", :game_builder_id => nil, :created_at => "2013-12-12 15:42:28", :updated_at => "2013-12-12 15:42:28" }
])



Message.create!([
  { :content => "6 3", :game_id => 2, :created_at => "2013-12-12 15:15:38", :updated_at => "2013-12-12 15:15:38", :name => " rolled", :source => "computer" },
  { :content => "4 5", :game_id => 2, :created_at => "2013-12-12 15:15:39", :updated_at => "2013-12-12 15:15:39", :name => " rolled", :source => "computer" },
  { :content => "6 3", :game_id => 2, :created_at => "2013-12-12 15:15:40", :updated_at => "2013-12-12 15:15:40", :name => " rolled", :source => "computer" }
])



Token.create!([
  { :name => nil, :x_coordinate => 232, :y_coordinate => 158, :game_id => 1, :created_at => "2013-12-12 15:14:52", :updated_at => "2013-12-12 15:14:52", :image_1 => "checkers_red_1.png", :state => 0, :image_0 => "checkers_red_0.png", :flippable => true },
  { :name => nil, :x_coordinate => 381, :y_coordinate => 12, :game_id => 1, :created_at => "2013-12-12 15:14:52", :updated_at => "2013-12-12 15:14:52", :image_1 => "checkers_red_1.png", :state => 0, :image_0 => "checkers_red_0.png", :flippable => true },
  { :name => nil, :x_coordinate => 232, :y_coordinate => 11, :game_id => 1, :created_at => "2013-12-12 15:14:52", :updated_at => "2013-12-12 15:14:52", :image_1 => "checkers_red_1.png", :state => 0, :image_0 => "checkers_red_0.png", :flippable => true },
  { :name => nil, :x_coordinate => 527, :y_coordinate => 10, :game_id => 1, :created_at => "2013-12-12 15:14:52", :updated_at => "2013-12-12 15:14:52", :image_1 => "checkers_red_1.png", :state => 0, :image_0 => "checkers_red_0.png", :flippable => true },
  { :name => nil, :x_coordinate => 380, :y_coordinate => 160, :game_id => 1, :created_at => "2013-12-12 15:14:52", :updated_at => "2013-12-12 15:14:52", :image_1 => "checkers_red_1.png", :state => 0, :image_0 => "checkers_red_0.png", :flippable => true },
  { :name => nil, :x_coordinate => 157, :y_coordinate => 86, :game_id => 1, :created_at => "2013-12-12 15:14:52", :updated_at => "2013-12-12 15:14:52", :image_1 => "checkers_red_1.png", :state => 0, :image_0 => "checkers_red_0.png", :flippable => true },
  { :name => nil, :x_coordinate => 83, :y_coordinate => 12, :game_id => 1, :created_at => "2013-12-12 15:14:52", :updated_at => "2013-12-12 15:14:52", :image_1 => "checkers_red_1.png", :state => 0, :image_0 => "checkers_red_0.png", :flippable => true },
  { :name => nil, :x_coordinate => 452, :y_coordinate => 88, :game_id => 1, :created_at => "2013-12-12 15:14:52", :updated_at => "2013-12-12 15:14:52", :image_1 => "checkers_red_1.png", :state => 0, :image_0 => "checkers_red_0.png", :flippable => true },
  { :name => nil, :x_coordinate => 306, :y_coordinate => 87, :game_id => 1, :created_at => "2013-12-12 15:14:52", :updated_at => "2013-12-12 15:14:52", :image_1 => "checkers_red_1.png", :state => 0, :image_0 => "checkers_red_0.png", :flippable => true },
  { :name => nil, :x_coordinate => 11, :y_coordinate => 87, :game_id => 1, :created_at => "2013-12-12 15:14:52", :updated_at => "2013-12-12 15:14:52", :image_1 => "checkers_red_1.png", :state => 0, :image_0 => "checkers_red_0.png", :flippable => true },
  { :name => nil, :x_coordinate => 82, :y_coordinate => 160, :game_id => 1, :created_at => "2013-12-12 15:14:52", :updated_at => "2013-12-12 15:14:52", :image_1 => "checkers_red_1.png", :state => 0, :image_0 => "checkers_red_0.png", :flippable => true },
  { :name => nil, :x_coordinate => 529, :y_coordinate => 157, :game_id => 1, :created_at => "2013-12-12 15:14:52", :updated_at => "2013-12-12 15:14:52", :image_1 => "checkers_red_1.png", :state => 0, :image_0 => "checkers_red_0.png", :flippable => true },
  { :name => nil, :x_coordinate => 454, :y_coordinate => 532, :game_id => 1, :created_at => "2013-12-12 15:14:52", :updated_at => "2013-12-12 15:14:52", :image_1 => "checkers_grey_1.png", :state => 0, :image_0 => "checkers_grey_0.png", :flippable => true },
  { :name => nil, :x_coordinate => 305, :y_coordinate => 534, :game_id => 1, :created_at => "2013-12-12 15:14:52", :updated_at => "2013-12-12 15:14:52", :image_1 => "checkers_grey_1.png", :state => 0, :image_0 => "checkers_grey_0.png", :flippable => true },
  { :name => nil, :x_coordinate => 306, :y_coordinate => 382, :game_id => 1, :created_at => "2013-12-12 15:14:52", :updated_at => "2013-12-12 15:14:52", :image_1 => "checkers_grey_1.png", :state => 0, :image_0 => "checkers_grey_0.png", :flippable => true },
  { :name => nil, :x_coordinate => 156, :y_coordinate => 382, :game_id => 1, :created_at => "2013-12-12 15:14:52", :updated_at => "2013-12-12 15:14:52", :image_1 => "checkers_grey_1.png", :state => 0, :image_0 => "checkers_grey_0.png", :flippable => true },
  { :name => nil, :x_coordinate => 380, :y_coordinate => 459, :game_id => 1, :created_at => "2013-12-12 15:14:52", :updated_at => "2013-12-12 15:14:52", :image_1 => "checkers_grey_1.png", :state => 0, :image_0 => "checkers_grey_0.png", :flippable => true },
  { :name => nil, :x_coordinate => 531, :y_coordinate => 460, :game_id => 1, :created_at => "2013-12-12 15:14:52", :updated_at => "2013-12-12 15:14:52", :image_1 => "checkers_grey_1.png", :state => 0, :image_0 => "checkers_grey_0.png", :flippable => true },
  { :name => nil, :x_coordinate => 230, :y_coordinate => 459, :game_id => 1, :created_at => "2013-12-12 15:14:52", :updated_at => "2013-12-12 15:14:52", :image_1 => "checkers_grey_1.png", :state => 0, :image_0 => "checkers_grey_0.png", :flippable => true },
  { :name => nil, :x_coordinate => 157, :y_coordinate => 532, :game_id => 1, :created_at => "2013-12-12 15:14:52", :updated_at => "2013-12-12 15:14:52", :image_1 => "checkers_grey_1.png", :state => 0, :image_0 => "checkers_grey_0.png", :flippable => true },
  { :name => nil, :x_coordinate => 10, :y_coordinate => 532, :game_id => 1, :created_at => "2013-12-12 15:14:52", :updated_at => "2013-12-12 15:14:52", :image_1 => "checkers_grey_1.png", :state => 0, :image_0 => "checkers_grey_0.png", :flippable => true },
  { :name => nil, :x_coordinate => 81, :y_coordinate => 458, :game_id => 1, :created_at => "2013-12-12 15:14:52", :updated_at => "2013-12-12 15:14:52", :image_1 => "checkers_grey_1.png", :state => 0, :image_0 => "checkers_grey_0.png", :flippable => true },
  { :name => nil, :x_coordinate => 453, :y_coordinate => 381, :game_id => 1, :created_at => "2013-12-12 15:14:52", :updated_at => "2013-12-12 15:14:52", :image_1 => "checkers_grey_1.png", :state => 0, :image_0 => "checkers_grey_0.png", :flippable => true },
  { :name => nil, :x_coordinate => 10, :y_coordinate => 386, :game_id => 1, :created_at => "2013-12-12 15:14:52", :updated_at => "2013-12-12 15:14:52", :image_1 => "checkers_grey_1.png", :state => 0, :image_0 => "checkers_grey_0.png", :flippable => true },
  { :name => "backgammon", :x_coordinate => 10, :y_coordinate => 10, :game_id => 2, :created_at => "2013-12-12 15:15:35", :updated_at => "2013-12-12 15:15:35", :image_1 => "test_token.png", :state => 0, :image_0 => "test_token.png", :flippable => false },
  { :name => "backgammon", :x_coordinate => 10, :y_coordinate => 10, :game_id => 2, :created_at => "2013-12-12 15:15:35", :updated_at => "2013-12-12 15:15:35", :image_1 => "test_token.png", :state => 0, :image_0 => "test_token.png", :flippable => false },
  { :name => "backgammon", :x_coordinate => 10, :y_coordinate => 10, :game_id => 2, :created_at => "2013-12-12 15:15:35", :updated_at => "2013-12-12 15:15:35", :image_1 => "test_token.png", :state => 0, :image_0 => "test_token.png", :flippable => false },
  { :name => "backgammon", :x_coordinate => 10, :y_coordinate => 10, :game_id => 2, :created_at => "2013-12-12 15:15:35", :updated_at => "2013-12-12 15:15:35", :image_1 => "test_token.png", :state => 0, :image_0 => "test_token.png", :flippable => false },
  { :name => "backgammon", :x_coordinate => 10, :y_coordinate => 10, :game_id => 2, :created_at => "2013-12-12 15:15:35", :updated_at => "2013-12-12 15:15:35", :image_1 => "test_token.png", :state => 0, :image_0 => "test_token.png", :flippable => false },
  { :name => "backgammon", :x_coordinate => 10, :y_coordinate => 10, :game_id => 2, :created_at => "2013-12-12 15:15:35", :updated_at => "2013-12-12 15:15:35", :image_1 => "test_token.png", :state => 0, :image_0 => "test_token.png", :flippable => false },
  { :name => "backgammon", :x_coordinate => 10, :y_coordinate => 10, :game_id => 2, :created_at => "2013-12-12 15:15:35", :updated_at => "2013-12-12 15:15:35", :image_1 => "test_token.png", :state => 0, :image_0 => "test_token.png", :flippable => false },
  { :name => "backgammon", :x_coordinate => 10, :y_coordinate => 10, :game_id => 2, :created_at => "2013-12-12 15:15:35", :updated_at => "2013-12-12 15:15:35", :image_1 => "test_token.png", :state => 0, :image_0 => "test_token.png", :flippable => false },
  { :name => "backgammon", :x_coordinate => 10, :y_coordinate => 10, :game_id => 2, :created_at => "2013-12-12 15:15:35", :updated_at => "2013-12-12 15:15:35", :image_1 => "test_token.png", :state => 0, :image_0 => "test_token.png", :flippable => false },
  { :name => "backgammon", :x_coordinate => 10, :y_coordinate => 10, :game_id => 2, :created_at => "2013-12-12 15:15:35", :updated_at => "2013-12-12 15:15:35", :image_1 => "test_token.png", :state => 0, :image_0 => "test_token.png", :flippable => false },
  { :name => "backgammon", :x_coordinate => 10, :y_coordinate => 10, :game_id => 2, :created_at => "2013-12-12 15:15:35", :updated_at => "2013-12-12 15:15:35", :image_1 => "test_token.png", :state => 0, :image_0 => "test_token.png", :flippable => false },
  { :name => "backgammon", :x_coordinate => 10, :y_coordinate => 10, :game_id => 2, :created_at => "2013-12-12 15:15:35", :updated_at => "2013-12-12 15:15:35", :image_1 => "test_token.png", :state => 0, :image_0 => "test_token.png", :flippable => false },
  { :name => "backgammon", :x_coordinate => 10, :y_coordinate => 10, :game_id => 2, :created_at => "2013-12-12 15:15:35", :updated_at => "2013-12-12 15:15:35", :image_1 => "test_token.png", :state => 0, :image_0 => "test_token.png", :flippable => false },
  { :name => "backgammon", :x_coordinate => 10, :y_coordinate => 10, :game_id => 2, :created_at => "2013-12-12 15:15:35", :updated_at => "2013-12-12 15:15:35", :image_1 => "test_token.png", :state => 0, :image_0 => "test_token.png", :flippable => false },
  { :name => "backgammon", :x_coordinate => 10, :y_coordinate => 10, :game_id => 2, :created_at => "2013-12-12 15:15:35", :updated_at => "2013-12-12 15:15:35", :image_1 => "test_token.png", :state => 0, :image_0 => "test_token.png", :flippable => false },
  { :name => "backgammon", :x_coordinate => 0, :y_coordinate => 0, :game_id => 2, :created_at => "2013-12-12 15:15:35", :updated_at => "2013-12-12 15:15:35", :image_1 => "test2.png", :state => 0, :image_0 => "test2.png", :flippable => false },
  { :name => "backgammon", :x_coordinate => 0, :y_coordinate => 0, :game_id => 2, :created_at => "2013-12-12 15:15:35", :updated_at => "2013-12-12 15:15:35", :image_1 => "test2.png", :state => 0, :image_0 => "test2.png", :flippable => false },
  { :name => "backgammon", :x_coordinate => 0, :y_coordinate => 0, :game_id => 2, :created_at => "2013-12-12 15:15:35", :updated_at => "2013-12-12 15:15:35", :image_1 => "test2.png", :state => 0, :image_0 => "test2.png", :flippable => false },
  { :name => "backgammon", :x_coordinate => 0, :y_coordinate => 0, :game_id => 2, :created_at => "2013-12-12 15:15:35", :updated_at => "2013-12-12 15:15:35", :image_1 => "test2.png", :state => 0, :image_0 => "test2.png", :flippable => false },
  { :name => "backgammon", :x_coordinate => 0, :y_coordinate => 0, :game_id => 2, :created_at => "2013-12-12 15:15:35", :updated_at => "2013-12-12 15:15:35", :image_1 => "test2.png", :state => 0, :image_0 => "test2.png", :flippable => false },
  { :name => "backgammon", :x_coordinate => 0, :y_coordinate => 0, :game_id => 2, :created_at => "2013-12-12 15:15:35", :updated_at => "2013-12-12 15:15:35", :image_1 => "test2.png", :state => 0, :image_0 => "test2.png", :flippable => false },
  { :name => "backgammon", :x_coordinate => 0, :y_coordinate => 0, :game_id => 2, :created_at => "2013-12-12 15:15:35", :updated_at => "2013-12-12 15:15:35", :image_1 => "test2.png", :state => 0, :image_0 => "test2.png", :flippable => false },
  { :name => "backgammon", :x_coordinate => 0, :y_coordinate => 0, :game_id => 2, :created_at => "2013-12-12 15:15:35", :updated_at => "2013-12-12 15:15:35", :image_1 => "test2.png", :state => 0, :image_0 => "test2.png", :flippable => false },
  { :name => "backgammon", :x_coordinate => 0, :y_coordinate => 0, :game_id => 2, :created_at => "2013-12-12 15:15:35", :updated_at => "2013-12-12 15:15:35", :image_1 => "test2.png", :state => 0, :image_0 => "test2.png", :flippable => false },
  { :name => "backgammon", :x_coordinate => 0, :y_coordinate => 0, :game_id => 2, :created_at => "2013-12-12 15:15:35", :updated_at => "2013-12-12 15:15:35", :image_1 => "test2.png", :state => 0, :image_0 => "test2.png", :flippable => false },
  { :name => "backgammon", :x_coordinate => 0, :y_coordinate => 0, :game_id => 2, :created_at => "2013-12-12 15:15:35", :updated_at => "2013-12-12 15:15:35", :image_1 => "test2.png", :state => 0, :image_0 => "test2.png", :flippable => false },
  { :name => "backgammon", :x_coordinate => 0, :y_coordinate => 0, :game_id => 2, :created_at => "2013-12-12 15:15:35", :updated_at => "2013-12-12 15:15:35", :image_1 => "test2.png", :state => 0, :image_0 => "test2.png", :flippable => false },
  { :name => "backgammon", :x_coordinate => 0, :y_coordinate => 0, :game_id => 2, :created_at => "2013-12-12 15:15:35", :updated_at => "2013-12-12 15:15:35", :image_1 => "test2.png", :state => 0, :image_0 => "test2.png", :flippable => false },
  { :name => "backgammon", :x_coordinate => 0, :y_coordinate => 0, :game_id => 2, :created_at => "2013-12-12 15:15:35", :updated_at => "2013-12-12 15:15:35", :image_1 => "test2.png", :state => 0, :image_0 => "test2.png", :flippable => false },
  { :name => "backgammon", :x_coordinate => 0, :y_coordinate => 0, :game_id => 2, :created_at => "2013-12-12 15:15:35", :updated_at => "2013-12-12 15:15:35", :image_1 => "test2.png", :state => 0, :image_0 => "test2.png", :flippable => false },
  { :name => nil, :x_coordinate => 234, :y_coordinate => 163, :game_id => 3, :created_at => "2013-12-12 15:42:28", :updated_at => "2013-12-12 16:26:04", :image_1 => "checker_red_king.png", :state => 0, :image_0 => "checker_red.png", :flippable => true },
  { :name => nil, :x_coordinate => 381, :y_coordinate => 12, :game_id => 3, :created_at => "2013-12-12 15:42:28", :updated_at => "2013-12-12 16:03:19", :image_1 => "checker_red_king.png", :state => 0, :image_0 => "checker_red.png", :flippable => true },
  { :name => nil, :x_coordinate => 234, :y_coordinate => 12, :game_id => 3, :created_at => "2013-12-12 15:42:28", :updated_at => "2013-12-12 16:23:00", :image_1 => "checker_red_king.png", :state => 0, :image_0 => "checker_red.png", :flippable => true },
  { :name => nil, :x_coordinate => 459, :y_coordinate => 85, :game_id => 3, :created_at => "2013-12-12 15:42:28", :updated_at => "2013-12-12 16:06:20", :image_1 => "checker_red_king.png", :state => 0, :image_0 => "checker_red.png", :flippable => true },
  { :name => nil, :x_coordinate => 378, :y_coordinate => 162, :game_id => 3, :created_at => "2013-12-12 15:42:28", :updated_at => "2013-12-12 16:06:06", :image_1 => "checker_red_king.png", :state => 0, :image_0 => "checker_red.png", :flippable => true },
  { :name => nil, :x_coordinate => 531, :y_coordinate => 9, :game_id => 3, :created_at => "2013-12-12 15:42:28", :updated_at => "2013-12-12 16:06:29", :image_1 => "checker_red_king.png", :state => 0, :image_0 => "checker_red.png", :flippable => true },
  { :name => nil, :x_coordinate => 80, :y_coordinate => 11, :game_id => 3, :created_at => "2013-12-12 15:42:28", :updated_at => "2013-12-12 16:03:59", :image_1 => "checker_red_king.png", :state => 0, :image_0 => "checker_red.png", :flippable => true },
  { :name => nil, :x_coordinate => 306, :y_coordinate => 86, :game_id => 3, :created_at => "2013-12-12 15:42:28", :updated_at => "2013-12-12 16:03:32", :image_1 => "checker_red_king.png", :state => 0, :image_0 => "checker_red.png", :flippable => true },
  { :name => nil, :x_coordinate => 156, :y_coordinate => 88, :game_id => 3, :created_at => "2013-12-12 15:42:28", :updated_at => "2013-12-12 16:28:47", :image_1 => "checker_red_king.png", :state => 0, :image_0 => "checker_red.png", :flippable => true },
  { :name => nil, :x_coordinate => 6, :y_coordinate => 86, :game_id => 3, :created_at => "2013-12-12 15:42:28", :updated_at => "2013-12-12 16:03:25", :image_1 => "checker_red_king.png", :state => 0, :image_0 => "checker_red.png", :flippable => true },
  { :name => nil, :x_coordinate => 77, :y_coordinate => 161, :game_id => 3, :created_at => "2013-12-12 15:42:28", :updated_at => "2013-12-12 16:25:59", :image_1 => "checker_red_king.png", :state => 0, :image_0 => "checker_red.png", :flippable => true },
  { :name => nil, :x_coordinate => 528, :y_coordinate => 161, :game_id => 3, :created_at => "2013-12-12 15:42:28", :updated_at => "2013-12-12 16:06:03", :image_1 => "checker_red_king.png", :state => 0, :image_0 => "checker_red.png", :flippable => true },
  { :name => nil, :x_coordinate => 456, :y_coordinate => 533, :game_id => 3, :created_at => "2013-12-12 15:42:28", :updated_at => "2013-12-12 16:28:44", :image_1 => "checker_black_king.png", :state => 0, :image_0 => "checker_black.png", :flippable => true },
  { :name => nil, :x_coordinate => 308, :y_coordinate => 533, :game_id => 3, :created_at => "2013-12-12 15:42:28", :updated_at => "2013-12-12 16:15:18", :image_1 => "checker_black_king.png", :state => 0, :image_0 => "checker_black.png", :flippable => true },
  { :name => nil, :x_coordinate => 155, :y_coordinate => 387, :game_id => 3, :created_at => "2013-12-12 15:42:28", :updated_at => "2013-12-12 16:28:37", :image_1 => "checker_black_king.png", :state => 0, :image_0 => "checker_black.png", :flippable => true },
  { :name => nil, :x_coordinate => 304, :y_coordinate => 386, :game_id => 3, :created_at => "2013-12-12 15:42:28", :updated_at => "2013-12-12 16:26:24", :image_1 => "checker_black_king.png", :state => 0, :image_0 => "checker_black.png", :flippable => true },
  { :name => nil, :x_coordinate => 381, :y_coordinate => 458, :game_id => 3, :created_at => "2013-12-12 15:42:28", :updated_at => "2013-12-12 16:28:40", :image_1 => "checker_black_king.png", :state => 0, :image_0 => "checker_black.png", :flippable => true },
  { :name => nil, :x_coordinate => 530, :y_coordinate => 459, :game_id => 3, :created_at => "2013-12-12 15:42:28", :updated_at => "2013-12-12 16:28:42", :image_1 => "checker_black_king.png", :state => 0, :image_0 => "checker_black.png", :flippable => true },
  { :name => nil, :x_coordinate => 231, :y_coordinate => 456, :game_id => 3, :created_at => "2013-12-12 15:42:28", :updated_at => "2013-12-12 16:15:11", :image_1 => "checker_black_king.png", :state => 0, :image_0 => "checker_black.png", :flippable => true },
  { :name => nil, :x_coordinate => 160, :y_coordinate => 531, :game_id => 3, :created_at => "2013-12-12 15:42:28", :updated_at => "2013-12-12 16:15:15", :image_1 => "checker_black_king.png", :state => 0, :image_0 => "checker_black.png", :flippable => true },
  { :name => nil, :x_coordinate => 10, :y_coordinate => 531, :game_id => 3, :created_at => "2013-12-12 15:42:28", :updated_at => "2013-12-12 16:15:13", :image_1 => "checker_black_king.png", :state => 0, :image_0 => "checker_black.png", :flippable => true },
  { :name => nil, :x_coordinate => 80, :y_coordinate => 455, :game_id => 3, :created_at => "2013-12-12 15:42:28", :updated_at => "2013-12-12 16:16:25", :image_1 => "checker_black_king.png", :state => 0, :image_0 => "checker_black.png", :flippable => true },
  { :name => nil, :x_coordinate => 454, :y_coordinate => 384, :game_id => 3, :created_at => "2013-12-12 15:42:28", :updated_at => "2013-12-12 16:14:40", :image_1 => "checker_black_king.png", :state => 0, :image_0 => "checker_black.png", :flippable => true },
  { :name => nil, :x_coordinate => 9, :y_coordinate => 382, :game_id => 3, :created_at => "2013-12-12 15:42:28", :updated_at => "2013-12-12 16:16:23", :image_1 => "checker_black_king.png", :state => 0, :image_0 => "checker_black.png", :flippable => true }
])


